app/controllers/StartController.scala, app/controllers/UnauthorisedController.scala, app/controllers/actions/AuthAction.scala, app/forms/ConsignmentReferences.scala, app/forms/common/Date.scala, test/connectors/CustomsDeclareExportsMovementsConnectorSpec.scala, test/controllers/ConsignmentReferencesControllerSpec.scala, test/controllers/LocationControllerSpec.scala, test/forms/ConsignmentReferencesSpec.scala, test/forms/DepartureDetailsSpec.scala
This is just to allow a valid EORI to be entered as part of the arrival 
and departure journeys.
with @NC-1234
=> CEDS-1348 Allow valid EORI numbers

build.sbt, project/AppDependencies.scala, project/plugins.sbt
Our coverage in this repo is around 83%. The coverage level was set as 85%.
This cases failing precheck from few months.
=> CEDS-1219 Update for dependency and change for coverage

app/forms/ConsignmentReferences.scala, app/forms/Transport.scala, app/utils/validators/forms/FieldValidator.scala, conf/messages.en, test/controllers/ConsignmentReferencesControllerSpec.scala, test/forms/ConsignmentReferencesSpec.scala
* Validate EORI and MUCR/DUCR
* Validate two letter country codes
=> CEDS-1257 Review Arrive & Depart Validation

app/controllers/NotificationsController.scala, app/models/Movement.scala, app/models/Notification.scala, app/views/movements.scala.html, app/views/notifications.scala.html, test/views/MovementsViewSpec.scala
Reverts hmrc/customs-movements-frontend#35
=> Revert "Fix for movements and notifications"

app/metrics/MovementsMetrics.scala
Now are too domain specific and does not carry any information
=> CEDS-1587 Use descriptive name for metrics

test/base/MovementApp.scala, test/views/base/ViewSpec.scala
Fix errors on application creation in tests
=> Remove SharedMetricEach time aplication is created

test/controllers/consolidations/AssociateDucrSummaryControllerSpec.scala, test/controllers/consolidations/DisassociateDucrControllerSpec.scala, test/controllers/consolidations/ShutMucrConfirmationControllerSpec.scala, test/controllers/consolidations/ShutMucrControllerSpec.scala, test/filters/ApplicationFiltersIntegrationTest.scala, test/unit/controllers/NotificationsControllerSpec.scala, test/unit/controllers/StartControllerSpec.scala
Move unit controller tests to unit package
=> Move tests to use MovementBaseSpec on integration tests.

app/connectors/CustomsDeclareExportsMovementsConnector.scala, app/controllers/SummaryController.scala, app/controllers/consolidations/AssociateDucrSummaryController.scala, app/controllers/consolidations/DisassociateDucrController.scala, app/controllers/consolidations/ShutMucrController.scala, test/resources/logback-test.xml
Adjust logging level to platform guides.
Most of non application errors (missing data in db, bad requests) should be on warn level rather then error.
=> Ceds 1602 - Review logging level

app/controllers/NotificationsController.scala, app/models/viewmodels/decoder/ActionCode.scala, app/models/viewmodels/decoder/CodeWithContentKey.scala, app/models/viewmodels/decoder/CrcCode.scala, app/models/viewmodels/decoder/ErrorCode.scala, app/models/viewmodels/decoder/RoeCode.scala, app/models/viewmodels/decoder/SoeCode.scala, app/models/viewmodels/notificationspage/ControlResponseConverter.scala, app/models/viewmodels/notificationspage/MovementResponseConverter.scala, app/models/viewmodels/notificationspage/MovementTotalsResponseConverter.scala, app/models/viewmodels/notificationspage/NotificationPageSingleElementContentBuilder.scala, app/models/viewmodels/notificationspage/NotificationPageSingleElementConverter.scala, app/models/viewmodels/notificationspage/NotificationPageSingleElementFactory.scala, app/models/viewmodels/notificationspage/NotificationsPageSingleElement.scala, app/modules/DateTimeFormatterModule.scala, app/views/components/notifications_single_element.scala.html, app/views/notifications.scala.html, conf/application.conf, test/base/MockFactory.scala, test/models/viewmodels/notificationspage/ControlResponseContentBuilderSpec.scala, test/models/viewmodels/notificationspage/ControlResponseConverterSpec.scala, test/models/viewmodels/notificationspage/MovementResponseConverterSpec.scala, test/models/viewmodels/notificationspage/MovementTotalsResponseConverterSpec.scala, test/models/viewmodels/notificationspage/NotificationPageSingleElementFactorySpec.scala, test/testdata/CommonTestData.scala, test/unit/controllers/NotificationsControllerSpec.scala, test/views/NotificationsViewSpec.scala
This PR sets ground for the tickets coming next for notifications page.
In one of the commits it addressed the change of logging level for unknown notification error codes. For more details look into commit message.
=> Notifications page element factory refactor

app/controllers/consolidations/AssociateDucrSummaryController.scala, app/controllers/consolidations/DisassociateDucrController.scala, app/controllers/consolidations/ShutMucrController.scala, app/services/SubmissionService.scala, app/services/audit/AuditService.scala, test/base/MockFactory.scala, test/base/MockSubmissionService.scala, test/services/SubmissionServiceSpec.scala, test/services/audit/AuditServiceSpec.scala, test/unit/controllers/consolidations/DisassociateDucrControllerSpec.scala
CEDS-1681 Audit Movements DUCR Association Submission
CEDS-1683 Audit Movements DUCR Disassociate Submission
CEDS-1684 Audit Shut a DUCR Submission
=> CEDS-1681 Audit Movement Submissions

app/assets/stylesheets/partials/_step-by-step-navigation.scss, app/models/viewmodels/decoder/ActionCode.scala, app/models/viewmodels/decoder/CRCCode.scala, app/models/viewmodels/decoder/ErrorCode.scala, app/models/viewmodels/decoder/ICSCode.scala, app/models/viewmodels/decoder/ROECode.scala, app/models/viewmodels/decoder/SOECode.scala, app/views/notifications.scala.html
This is a quick fix for Notifications page styling and added documentation for codes with some explanation on their origin.
=> CEDS-1662 prep

app/views/components/table_row_no_change_link.scala.html, app/views/summary/departure_summary_page.scala.html
remove extra bracket
fix data item alignment
=> CEDS-1746 - Departure Summary Page display issues

app/assets/stylesheets/partials/_layout.scss, app/views/start_page.scala.html, test/views/StartViewSpec.scala
Just some minor changes to align with Declarations code
=> CEDS-1693 start page polishing

app/services/audit/AuditService.scala, test/services/audit/AuditServiceSpec.scala
This was the feedback from TxM team.
=> CEDS-1675 Change the case of TXM ids to camelcase

app/models/external/requests/ConsolidationRequestFactory.scala
This is a minimal PR to prepare the FE from the BE changes to `Consolidation` message
=> CEDS-1812-disassociate-mucr

app/connectors/CustomsDeclareExportsMovementsConnector.scala, app/controllers/MovementsController.scala, app/controllers/NotificationsController.scala, app/models/submissions/SubmissionFrontendModel.scala, conf/application.conf, test/base/MockAuthConnector.scala, test/base/MockCustomsExportsMovement.scala, test/base/MockFactory.scala, test/models/viewmodels/notificationspage/NotificationPageSingleElementFactorySpec.scala, test/testdata/ConsolidationTestData.scala, test/testdata/MovementsTestData.scala, test/unit/base/ControllerSpec.scala, test/unit/connectors/CustomsDeclareExportsMovementsConnectorSpec.scala, test/unit/controllers/MovementsControllerSpec.scala, test/unit/controllers/NotificationsControllerSpec.scala, test/unit/models/submissions/SubmissionFrontendModelSpec.scala, test/views/MovementsViewSpec.scala
Frontend update regarding changes in the backend.
=> CEDS-1826 fetch changes

app/services/audit/AuditService.scala
This is a request from Titi from the TxM team. The opinion is that TxM
wants to standardise the payloads format.
=> CEDS-1675 Lower case the audit transactionName value

app/forms/MovementBuilder.scala, app/forms/common/Date.scala, app/forms/common/Time.scala, app/views/components/input_time.scala.html, conf/messages.en, test/forms/common/DateSpec.scala, test/forms/common/TimeSpec.scala
Use Instant format for communication to backend
Use double digit formatting on form level
Use single error for invalid data
=> CEDS-1875 Fix formatting with double digits

app/views/arrival_details.scala.html, app/views/components/page_title.scala.html, app/views/departure_details.scala.html, app/views/location.scala.html, app/views/movements.scala.html, app/views/summary/arrival_summary_page.scala.html, app/views/summary/departure_summary_page.scala.html, app/views/transport.scala.html, test/helpers/views/ArrivalDetailsMessages.scala
Passing only the messages key does not allow to pass varargs and
therefore is not sufficient anymore. It is a safer and more flexible
solution to just pass the text to be displayed itself.
=> Change page_title not to call Messages in it

app/views/arrival_details.scala.html, app/views/arrival_reference.scala.html, app/views/associate_ucr.scala.html, app/views/associate_ucr_summary.scala.html, app/views/choice_page.scala.html, app/views/components/submit_button.scala.html, app/views/consignment_references.scala.html, app/views/departure_details.scala.html, app/views/disassociate_ucr.scala.html, app/views/disassociate_ucr_confirmation.scala.html, app/views/disassociate_ucr_summary.scala.html, app/views/location.scala.html, app/views/main_template.scala.html, app/views/movement_confirmation_page.scala.html, app/views/mucr_options.scala.html, app/views/notifications.scala.html, app/views/shut_mucr.scala.html, app/views/shut_mucr_summary.scala.html, app/views/summary/arrival_summary_page.scala.html, app/views/summary/departure_summary_page.scala.html, app/views/transport.scala.html, test/helpers/views/CommonMessages.scala, test/views/ArrivalReferenceViewSpec.scala, test/views/DepartureDetailsViewSpec.scala, test/views/LocationViewSpec.scala, test/views/TransportViewSpec.scala
Refactor submit button to take messages outside
Little reformatting templates where needed
=> CEDS-1390 Use Continue instead Save and Continue

app/controllers/SummaryController.scala, app/forms/MovementBuilder.scala, app/models/cache/Answers.scala, app/services/SubmissionService.scala, app/services/audit/AuditService.scala, app/services/audit/AuditType.scala, test/services/SubmissionServiceSpec.scala, test/services/audit/AuditServiceSpec.scala, test/testdata/MovementsTestData.scala
This PR introduces fixes to Audit events and adds missing tests for AuditService and SubmissionService.
=> Audit service enhancement

app/services/audit/AuditService.scala, app/services/audit/AuditType.scala, test/services/audit/AuditServiceSpec.scala
This PR introduces fixes to Audit events and adds missing tests for AuditService and SubmissionService.
=> Change AuditEvents contents

app/handlers/ErrorHandler.scala, project/AppDependencies.scala, test/it/ArrivalSpec.scala, test/it/AssociateUcrSpec.scala, test/it/ChoiceSpec.scala, test/it/DepartureSpec.scala, test/it/DissociateUcrSpec.scala, test/it/IntegrationSpec.scala, test/it/ShutMucrSpec.scala, test/unit/handlers/ErrorHandlerSpec.scala, test/unit/mocks/ErrorHandlerMocks.scala, test/util/connectors/AuditWiremockTestServer.scala, test/util/connectors/AuthWiremockTestServer.scala, test/util/connectors/MovementsBackendWiremockTestServer.scala, test/util/connectors/WiremockTestServer.scala, test/util/repository/TestMongoDB.scala
Copied and altered from Internal UI
=> CEDS-2022 IT Tests

test/unit/controllers/MovementDetailsControllerSpec.scala
There was a fixed date provided for MovementDetailsControllerSpec and since today it stopped to be correct. Changed that to be generated in the same way as the Date and Time for Arrival and Departure Details Specs.
=> Fix for MovementsDetails page

app/views/choice_page.scala.html, docs/Customs Declare Exports Movements AutoComplete.js, test/unit/views/ChoiceViewSpec.scala
Fix required for links in error summary to work
=> CEDS 2024 choice fix

app/controllers/ArrivalReferenceController.scala, app/views/arrival_reference.scala.html, app/views/associate_ucr.scala.html, app/views/components/gds/exportsInputText.scala.html, conf/messages, test/unit/controllers/ArrivalReferenceControllerSpec.scala, test/unit/views/ArrivalReferenceViewSpec.scala
Part of Switch movements service single text input pages to the gov design system
=> CEDS-2027  - arrival reference page

app/views/disassociate_ucr_confirmation.scala.html, app/views/shut_mucr_confirmation.scala.html, test/unit/views/DisassociateUcrConfirmationViewSpec.scala, test/unit/views/ShutMucrConfirmationViewSpec.scala
Finishes off the last two confirmation pages on this ticket
=> CEDS-2028 remaining confirmation pages

project/AppDependencies.scala
This should clear problem with “No primary node is available!”
=> CEDS Update simple-reactivemongo

app/models/viewmodels/decoder/CRCCode.scala, conf/messages-notification-codes-cds.en, conf/messages-notification-codes-exports.en, test/unit/models/viewmodels/decoder/CRCCodeSpec.scala
(See - CTAR-5076)
This involves re-defining the meaning of error code '102'
=> CEDS-1885 - Update arrive DUCR/MUCR error message when they don't exist

app/forms/Transport.scala, test/it/DepartureSpec.scala, test/unit/forms/TransportSpec.scala, test/unit/views/DepartureSummaryViewSpec.scala
*Reorder error messages
*Change test cases to conform to changed sequence
=> CEDS-1757: Rectification of order of error messages in transport screen

app/config/AppConfig.scala, app/mongock/MongockConfig.scala, app/mongock/changesets/CacheChangelog.java, project/AppDependencies.scala
-  add updated field to existing cache objects
=> BAU - add Mongock to movements frontend 

app/config/AppConfig.scala, app/controllers/ChoiceController.scala, app/features/Feature.scala, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes
This approach uses the existing mechanism which has the advantage of being dynamically changeable in test environments using 
`/customs-movements/test-only/feature/ileQuery/enabled` or 
`/customs-movements/test-only/feature/ileQuery/disabled`
=> BAU ileQuery feature switch

app/forms/DisassociateUcr.scala, test/unit/forms/AssociateUcrSpec.scala, test/unit/forms/DisassociateUcrSpec.scala
One of the new apply methods was incorrectly mapping the ucr
=> CEDS- 2174 dissociate bug

app/views/ile_query.scala.html, test/unit/views/IleQueryViewSpec.scala
Spotted during post-amigos - no way to return to start page.
=> CEDS 2175 add back link to find a consignment page

app/views/ile_query_timeout.scala.html, test/unit/views/IleQueryTimeoutViewSpec.scala
Added missing test from internal movements as well
=> CEDS-2159 - update back link on ile query timeout page

app/controllers/LocationController.scala, app/controllers/MovementDetailsController.scala, app/controllers/TransportController.scala, app/views/arrival_details.scala.html, app/views/departure_details.scala.html, test/unit/controllers/LocationControllerSpec.scala, test/unit/controllers/MovementDetailsControllerSpec.scala, test/unit/controllers/TransportControllerSpec.scala, test/unit/testdata/ConsolidationTestData.scala, test/unit/views/ArrivalDetailsViewSpec.scala, test/unit/views/DepartureDetailsViewSpec.scala, test/unit/views/MovementsViewSpec.scala
This PR fixes some unit tests and changes ConsignmentReference to be val in Controllers used for Arrival/Departure journey.
=> CEDS-2131 Unit Tests refactoring

app/views/start_page.scala.html, conf/messages, test/unit/views/StartViewSpec.scala
Include timezone information on External Movements start page
=> CEDS-2512 Explain timezones on Movements Start page

app/views/associateucr/mucr_options.scala.html, app/views/components/gds/exportsInputText.scala.html, app/views/ile_query.scala.html
Scales better with increased font size
=> CEDS-2529 - fixed width input fields for UCR for accessibility

app/controllers/MovementDetailsController.scala, app/views/arrival_details.scala.html, app/views/departure_details.scala.html, conf/messages, test/unit/controllers/MovementDetailsControllerSpec.scala, test/unit/views/ArrivalDetailsViewSpec.scala, test/unit/views/DepartureDetailsViewSpec.scala
=> CEDS-2089 - highlight date and time input fields when entered date

app/forms/common/Date.scala, app/forms/common/DateTimeErrors.scala, app/forms/common/Time.scala, app/utils/validators/forms/FieldValidator.scala, app/views/arrival_details.scala.html, app/views/components/gds/inputDate.scala.html, app/views/components/gds/inputTime.scala.html, app/views/departure_details.scala.html, conf/messages, test/unit/forms/common/DateSpec.scala, test/unit/forms/common/DateTimeErrorsSpec.scala, test/unit/forms/common/TimeSpec.scala, test/unit/views/ArrivalDetailsViewSpec.scala, test/unit/views/DepartureDetailsViewSpec.scala, test/unit/views/spec/ViewMatchers.scala
Includes
- highlighting of field level errors
- link to first field (day) in case of invalid date
=> CEDS-2089 - improved date/time error display

app/controllers/actions/AuthAction.scala, conf/application.conf, test/unit/base/MockAuthConnector.scala, test/unit/controllers/ControllerLayerSpec.scala, test/unit/controllers/actions/AuthActionSpec.scala, test/unit/controllers/actions/EoriAllowListSpec.scala
Change occurrences of 'whitelist' to 'allow list'
=> CEDS-2674 Replace 'whitelist' and 'blacklist' across services

app/models/viewmodels/decoder/CRCCode.scala, conf/messages-notification-codes-cds.en, conf/messages-notification-codes-exports.en, test/unit/models/viewmodels/decoder/CRCCodeSpec.scala
CRC code 102 content changed to 'Declaration has not arrived'
=> CEDS-2679 Update content for CRC code 102

app/views/components/confirmation_link.scala.html, app/views/components/gds/link.scala.html, app/views/components/ilequery/response_associated_consignments.scala.html, app/views/components/ilequery/response_buttons.scala.html, app/views/components/ilequery/response_parent.scala.html, app/views/confirmation_page.scala.html, app/views/ile_query.scala.html, app/views/movements.scala.html, app/views/user_signed_out.scala.html, conf/messages, test/unit/testdata/CommonTestData.scala, test/unit/views/MovementsViewSpec.scala
- Create option for visually hidden text to link component
- Use link with hidden text on movements page
- Refactor files which use link component to use Html data type instead of String
=> CEDS-2689 Add hidden text with context for movements

conf/messages
Add full stops to the end of error messages
=> CEDS-2736 Update error messages to be consistent

app/models/viewmodels/decoder/SOECode.scala, conf/messages-notification-codes-cds.en, conf/messages-notification-codes-exports.en, test/unit/models/viewmodels/decoder/SOECodeSpec.scala
For this PR to be ready, the content for code description needs to be added.
=> [WIP] CEDS-2734 Empty MUCR SOE code in EMR notification handling

app/repositories/CacheRepository.scala, app/repositories/IleQueryRepository.scala, app/repositories/RepositorySettings.scala
This is in order to increase resilience of the service.
=> CEDS-2776 Implement FailoverStrategy for all repository classes

app/config/AppConfig.scala, app/views/components/exit_survey.scala.html, app/views/confirmation_page.scala.html, app/views/user_signed_out.scala.html, conf/application.conf, conf/messages, test/unit/config/AppConfigSpec.scala, test/unit/views/ConfirmationPageViewSpec.scala, test/unit/views/UserSignedOutViewSpec.scala
Add link for Exit Survey on the following pages:
/customs-movements/movement-confirmation
/customs-movements/shut-mucr-confirmation
/customs-movements/dissociate-ucr-confirmation
/customs-movements/associate-ucr-confirmation
/customs-movements/you-have-signed-out
=> CEDS-2890 Set up Exit Survey for Movements

app/controllers/RootController.scala, app/handlers/ErrorHandler.scala, app/views/user_signed_out.scala.html, conf/app.routes, test/unit/controllers/RootControllerSpec.scala, test/unit/handlers/ErrorHandlerSpec.scala, test/unit/views/UserSignedOutViewSpec.scala
Create RootController to redirect to Choice page.
Remove references to 'Start' page and remove StartController.
=> CEDS-2965 Set Root Url to redirect to home page

conf/messages
Updating MUCR format error message and Consignment Reference radio
unselected error message.
=> CEDS-2947 Updating Validation Error Message More Additional work

app/services/Countries.scala, test/unit/views/DepartureSummaryViewSpec.scala
Keep country string formatting in line with other front-ends.
=> CEDS-3650 Correct country string formatting

app/views/notifications.scala.html, conf/messages, test/unit/views/NotificationsViewSpec.scala
Inspect the UCR value to determine if the value is a MUCR or a DUCR and display the appropriate label for each
=> CEDS-4063 Shows correct MUCR or DUCR lable on notification page

app/config/TdrUnauthorisedMsgConfig.scala, app/controllers/UnauthorisedController.scala, app/features/Feature.scala, app/views/unauthorisedEoriInTdr.scala.html, conf/application.conf, conf/messages, test/unit/controllers/UnauthorisedControllerSpec.scala, test/unit/views/UnauthorisedEoriInTdrViewSpec.scala
Display different content on Unauthorised page in TDR env
=> BAU Alter Unauth EORI message in TDR

conf/application.conf, project/plugins.sbt
Reverts hmrc/customs-movements-frontend#429
Reverting due to breaking some style and js functionality on site
=> Revert "CEDS-5089 GA4 Update the Content Security Policy"

app/controllers/actions/AuthAction.scala, test/unit/controllers/actions/AuthActionSpec.scala
Fix issue with not redirecting user to auth-stub/GG when NoSession thrown
=> CEDS-5387 Stop Movements FE throwing exceptions auth-stub fix
