hmrc/customs-movements-frontend

- app/views/arrival_details.scala.html
- app/views/choice_page.scala.html
- app/views/components/RadioOption.scala
- app/views/components/back_link.scala.html
- app/views/components/fields/RadioOption.scala
- app/views/components/input_radio.scala.html
- app/views/consignment_references.scala.html
- app/views/departure_details.scala.html
- app/views/goods_departed.scala.html
- app/views/location.scala.html
- app/views/start_page.scala.html
- app/views/summary/arrival_summary_page.scala.html
- app/views/summary/departure_summary_page.scala.html
- app/views/transport.scala.html
- build.sbt
- test/utils/RadioOptionSpec.scala
- test/views/ChoiceViewSpec.scala
IntelliJ struggles to render templates properly when there are two packages/classes imported with the same name.
For example twirl imports a `utils` package by default (part of Play). If we then import our own `utils` package the template compiles, but IntelliJ gives a tonne of errors. 
Given the fix was quick and easy I figured it was worth doing
> CEDS-1204 Clean up IntelliJ Errors

- app/config/AppConfig.scala
- app/connectors/CustomsDeclareExportsMovementsConnector.scala
- app/controllers/ChoiceController.scala
- app/controllers/MovementsController.scala
- app/models/Movement.scala
- app/views/movements.scala.html
- conf/app.routes
- conf/application.conf
- test/base/MockCustomsExportsMovement.scala
- test/controllers/ChoiceControllerSpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/services/MovementServiceSpec.scala
- test/views/MovementsViewSpec.scala
We do not really use that domain language here and we should not bring
submissions to the mix. These are movements.
This also included a fix for the movements backend url.
> CEDS-1072 Rename the submissions to movements

- app/connectors/CustomsDeclareExportsMovementsConnector.scala
- app/models/NotificationPresentation.scala
- app/models/UcrBlock.scala
- app/views/movements.scala.html
- app/views/notifications.scala.html
- test/base/testdata/CommonTestData.scala
- test/views/MovementsViewSpec.scala
Since this class is used for presentation only, it contains only
presentation-relevant fields. Backend should send Notification data
in the same format, decoupling presentation model from DB model.
> CEDS-1436 Replace Notification model with NotificationPresentationData

- app/forms/MucrOptions.scala
- test/controllers/consolidations/MucrOptionsControllerSpec.scala
Change to clear the value of the MUCR not being used when the form fails validation.   Previously we only captured one MUCR value (for either create or add).  If the user entered an invalid value into both fields and submitted the page they got an error highlighting the MUCR field that was wrong.  But if they when switched to the other MUCR field, that was populated with the 'other' MUCR value (i.e. not the one submitted).
We now clear (remove) the 'hidden' MUCR value on submission.   The other option was to leave the hidden MUCR value un-touched but as that MUCR may have been valid it was thought that this might confuse the users even more.
> CEDS-1419 - clear the un-used MUCR when validating the form

- build.sbt
- conf/messages.en
Changes to make view working correctly, but this `toLowerCase` smells. Probably it should be improved to make only first char to be lower case.
Changes in build.sbt related with warning. 
`[warn] Unable to process javascripts/google-tag-manager.js. Not found.`
Not sure that we should have `google-tag-manager`, but if yes probably it will be better to create a ticket for it and make everything in proper way.
> CEDS-1518 Fix for messages

- app/assets/stylesheets/partials/_step-by-step-navigation.scss
- app/views/components/notifications_single_element.scala.html
- app/views/notifications.scala.html
The element containing index was stretched across the whole width of the
element. It should be just a circle instead.
> CEDS-1509 Fix broken styles

- app/filters/Filters.scala
- app/filters/WhitelistIpFilter.scala
- conf/application.conf
- project/AppDependencies.scala
- test/filters/ApplicationFiltersIntegrationTest.scala
- test/filters/WhitelistIPFilterProviderSpec.scala
Use same aproch like in customs-declare-exports-frontend.
/healthcheck and /ping/ping must be excluded for docktor checks
> CEDS-1581 Add ip whitelist for service

- app/services/SubmissionService.scala
- app/services/audit/AuditService.scala
- test/services/SubmissionServiceSpec.scala
- test/services/audit/AuditServiceSpec.scala
Instead of having the DMS movement keys, we will use the human readable
version:
Arrival
Departure
Associate
Disassociate
ShutMucr
This fix also impacts CEDS-1683 and CEDS-1684
> CEDS-1681 Rename Audit Types

- app/forms/DepartureDetails.scala
- app/services/SubmissionService.scala
- app/services/audit/AuditService.scala
- test/services/audit/AuditServiceSpec.scala
Keystore which is the tech underlying the CacheMap encrypts the data, so
we need to get each entry and then transform it into Json.
This is another reason for us to move away from Keystore
> CEDS-1660 Audit Movements in Json format

- app/assets/javascripts/autocomplete.js
This is an element that is generated by JS on our pages that require
list codes.
I decided to wrap the `<input>` element with a `<label>` in order to
avoid having to name unique ids, since on some pages we have more than
one autocomplete element.
> CEDS-1119 Add Label to autocomplete element

- app/connectors/CustomsDeclareExportsMovementsConnector.scala
- app/controllers/MovementsController.scala
- test/unit/controllers/MovementsControllerSpec.scala
The algorithm is for matching Submissions with Notifications by their
conversation ID.
The time complexity used to be s * n, where:
- s - number of Submissions
- n - number of Notifications
For large amounts of those it would get slower quite quickly.
Additionally it was sorting Notifications before the process which was
unnecessary as they were being filtered later.
The new solution makes use of groupBy method and therefore comes down
to logarithmic complexity.
> CEDS-1860 Improve algorithm in ViewSubmissionsController

- app/controllers/ChoiceController.scala
- app/controllers/MovementConfirmationController.scala
- app/controllers/SummaryController.scala
- app/forms/Choice.scala
- app/handlers/ErrorHandler.scala
- app/metrics/MovementsMetrics.scala
- app/models/ReturnToStartException.scala
- app/services/SubmissionService.scala
- app/views/associate_ucr_confirmation.scala.html
- app/views/choice_page.scala.html
- app/views/components/confirmation_status_info.scala.html
- app/views/disassociate_ucr_confirmation.scala.html
- app/views/movement_confirmation_page.scala.html
- app/views/shut_mucr_confirmation.scala.html
- conf/app.routes
- test/handlers/ErrorHandlerSpec.scala
- test/unit/controllers/ChoiceControllerSpec.scala
- test/unit/controllers/MovementConfirmationControllerSpec.scala
- test/unit/controllers/SummaryControllerSpec.scala
- test/unit/controllers/consolidations/AssociateUcrConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/AssociateUcrControllerSpec.scala
- test/unit/controllers/consolidations/AssociateUcrSummaryControllerSpec.scala
- test/unit/controllers/consolidations/DisassociateUcrConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/DisassociateUcrControllerSpec.scala
- test/unit/controllers/consolidations/DisassociateUcrSummaryControllerSpec.scala
- test/unit/controllers/consolidations/MucrOptionsControllerSpec.scala
- test/views/AssociateDucrConfirmationViewSpec.scala
- test/views/ChoiceViewSpec.scala
- test/views/MovementConfirmationViewSpec.scala
Key Changes:
- Movements confirmation changed to POST/Redirect/GET
- Choice: `associateDUCR =>  associateUCR`
- Choice: `disossiateDUCR => disossiateUCR`
> CEDS-1940 Align behaviour with Internal UI

- app/views/components/back_link.scala.html
- test/views/ArrivalReferenceViewSpec.scala
- test/views/ChoiceViewSpec.scala
- test/views/DepartureDetailsViewSpec.scala
- test/views/LocationViewSpec.scala
- test/views/MucrOptionsViewSpec.scala
- test/views/TransportViewSpec.scala
- test/views/ViewSpec.scala
Change back button HTML id from `link-back` to `back-link`
This is to align ourselves with the GDS design system compoenent.
> CEDS-1976 Change back button id

- app/views/associate_ucr_summary.scala.html
- test/views/AssociateDucrSummaryViewSpec.scala
* I missed an updated of the mucr change tag id from `mucr-change` to
`associate_mucr-change`. This change is to align the ids with the same
format in other places.
* This change was already done in the acceptance tests suite and the
movements-regression tests failed.
> CEDS-1783 Amend associate MUCR change tag id

- app/views/arrival_details.scala.html
- app/views/arrival_reference.scala.html
- app/views/associate_ucr.scala.html
- app/views/associate_ucr_confirmation.scala.html
- app/views/associate_ucr_summary.scala.html
- app/views/choice_page.scala.html
- app/views/components/sectionHeader.scala.html
- app/views/consignment_references.scala.html
- app/views/departure_details.scala.html
- app/views/disassociate_ucr.scala.html
- app/views/disassociate_ucr_confirmation.scala.html
- app/views/disassociate_ucr_summary.scala.html
- app/views/gds_main_template.scala.html
- app/views/location.scala.html
- app/views/main_template.scala.html
- app/views/movement_confirmation_page.scala.html
- app/views/movements.scala.html
- app/views/mucr_options.scala.html
- app/views/notifications.scala.html
- app/views/shut_mucr.scala.html
- app/views/shut_mucr_confirmation.scala.html
- app/views/shut_mucr_summary.scala.html
- app/views/summary/arrival_summary_page.scala.html
- app/views/summary/departure_summary_page.scala.html
- app/views/transport.scala.html
- conf/messages
- test/unit/views/ConsignmentReferenceViewSpec.scala
- test/unit/views/DisassociateUcrConfirmationViewSpec.scala
- test/unit/views/MessagesStub.scala
- test/unit/views/MucrOptionsViewSpec.scala
- Refactored the Title component to try and prevent incorrect use.  Aim is to ensure that the page title is always rendered as <title> - <optional section> - <service name> - GOV.UK
- Refactored associate_ucr to use the new exportsInputText component
- Created new sectionHeader component for use with GDS pages
> CEDS-2024 refactor Title component

- app/views/components/gds/gds_main_template.scala.html
- app/views/components/gds/govuk_wrapper.scala.html
Still `lib/govuk-frontend/govuk/all.js` is looking for `image` that we don't have in assets folder and some fonts. Don't know how to solve those two problems.
Google tag manager is just line that add this script, but we don't have it, so unnecessary thing.
> CEDS-2087 Cleaning script references

- app/views/components/gds/gds_main_template.scala.html
- app/views/components/gds/govukFlexibleLayout.scala.html
The default govukLayout provided by play-frontend-govuk does not allow
for customizable page content width. Everything is encapsulated in
govuk-grid-column-two-thirds element.
The new component is a copy of the library's govukLayout but it is
passing the content as is, without adding wrapping elements.
The responsibility for this is moved to the client.
To choose new layout component you have to set useDefaultContentWidth to
false in gds_main_template.
> CEDS-2028 Add govukFlexibleLayout

- app/assets/stylesheets/customsdecexfrontend-app.scss
- app/assets/stylesheets/partials/_lists.scss
- app/views/start_page.scala.html
- conf/messages
- test/unit/controllers/NotificationsControllerSpec.scala
- test/unit/views/StartViewSpec.scala
**WORK DONE:**
* **Migrate Start page to GDS Design system**
As part of this work, we kept looking at the prototype, unfortunately 
how the Start page was designed in the prototype it composed of several
`govuk-grid-column-two-thirds` plus some `govuk-grid-column-one-third`.
Since the start page is not a critical page to the service, we have
brought it to the GDS design system, but kept the same layout as before.
Also the Dashed list does not exist as a component in the GDS design
system, so again, we have kept the same approach as before, by simply
using the a normal dash.
* **Import govuk-frontend/govuk assets as the last task**
In order to access all assets and load them correctly, the
`govuk-frontend/govuk` has to be the last imported library in this file.
This actually fixes the …
> CEDS-2028 Migrate Start page to GDS Design system

- app/controllers/consolidations/AssociateUcrConfirmationController.scala
- app/controllers/consolidations/DisassociateUcrConfirmationController.scala
- app/controllers/consolidations/ShutMucrConfirmationController.scala
- app/views/associate_ucr_confirmation.scala.html
- app/views/disassociate_ucr_confirmation.scala.html
- app/views/shut_mucr_confirmation.scala.html
- test/unit/controllers/consolidations/AssociateUcrConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/DisassociateUcrConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/ShutMucrConfirmationControllerSpec.scala
- test/unit/views/AssociateDucrConfirmationViewSpec.scala
- test/unit/views/DisassociateUcrConfirmationViewSpec.scala
- test/unit/views/ShutMucrConfirmationViewSpec.scala
During testing I noticed that one of the confirmation pages blew up when pressing refresh (due to a missing Flash key).
This PR is to standardise the way Flash keys are used (to be the same as MovementConfirmationController) whereby the key values are extracted by the controller and passed to the page.  Missing key/value results in a "ReturnToStart" exception.
> Confirmation page flash keys usage

- build.sbt
This is due to a failed deployment to `externaltest` environement where
an error was found:
```
java.lang.IllegalArgumentException: Last encoded character (before the
paddings if any) is a valid base 64 alphabet but not a possible value
```
This is to do with an incorrect sso encryption key being used in
externaltest and the latest version of `simple-reactivemongo` uses the
latest `commons-codec v1.13` which detects this as an issue and the
deployment fails.
This has been discussed with Colin Webb and Lewis Capaldi.
This is the last resort attempt to deploy the applications to
`externaltest` whilst HMRC Platform team look into the issue.
> CEDS-2029 Force use of commons-codec v1.12

- app/models/cache/Cache.scala
- app/mongobee/changesets/CacheChangelog.java
- added new "updated" field to cache model with default of "now"
- updated the db (using Mongobee) to add field to existing cache objects and add ttl index to cache collection
> CEDS-2164 - add TTL of 60 mins to cache

- app/models/cache/Cache.scala
Exising cache data cannot be migrated and we can't manually drop db in
prod., so new fields have to be optional.
> CEDS-2164 - make 'updated' field optional.

- conf/messages
A consistent naming convention must be displayed across all three CDS Exports services to provide users for a simplified experience and understanding.
The CDS Movements Exports service was modified to:
1) the service name changed to CDS Exports in the banners at the top of each page,
2) the service name changed to CDS Exports on the start page.
> CEDS-2057 - Rename the Export services

- app/views/components/ilequery/response_ducr_summary.scala.html
- conf/messages
- test/unit/views/components/ilequery/DucrSummaryViewSpec.scala
A queried DUCR must show the MRN on the results page. In contrast, there must be no MRN displayed on the results page when a MUCR is queried.
> CEDS-2216 - External Movements: Add MRN to Movements Query results page

- app/views/associateucr/associate_ucr_summary_no_change.scala.html
This is an alternative to https://github.com/hmrc/customs-movements-frontend/pull/282 which avoids having two summary lists
> CEDS-2609 - manually render summary list to avoid <span> bug 

- app/assets/stylesheets/partials/_autocomplete.scss
- app/views/ducr_part_details.scala.html
Change find Ducr Part input field to width-20 (works better with larger fonts)
> CEDS-2612 - auto-complete drop-down arrow location relative to font size

- app/views/associateucr/associate_ucr_summary.scala.html
- app/views/associateucr/associate_ucr_summary_no_change.scala.html
- app/views/disassociateucr/disassociate_ucr_summary.scala.html
- app/views/shutmucr/shut_mucr_summary.scala.html
- app/views/summary/arrival_summary_page.scala.html
- app/views/summary/departure_summary_page.scala.html
This change is to make Summary pages more accessible when used with
double-sized font.
Many words were split into multiple lines which was an issue.
> CEDS-2614 Change Summary pages to full width

- build.sbt
- project/TestPhases.scala
- project/build.properties
- project/plugins.sbt
- test/unit/services/SubmissionServiceSpec.scala
This version seems to be the last reliable version.
Higher versions contain some issues with importing a project. That would
need additional steps and workarounds to make it work.
> CEDS-2659 Upgrade SBT to 1.3.6

- app/config/AppConfig.scala
- app/views/components/gds/phaseBanner.scala.html
- conf/application.conf
- test/unit/views/PhaseBannerSpec.scala
As a part of Public Beta Readiness prep activities, every page
of the External Movements must have a feedback link at the
top left corner under black GOV.UK banner and next to BETA
blue box.
This sends the feedback to Splunk for later retrieval.
> [CEDS-2745] Add feedback link to banner in all the pages

- app/config/AppConfig.scala
- app/views/components/gds/gds_main_template.scala.html
- project/AppDependencies.scala
- test/unit/views/associateucr/AssociateUcrSummaryViewSpec.scala
- test/unit/views/associateucr/MucrOptionsViewSpec.scala
- test/unit/views/disassociateucr/DisassociateUcrSummaryViewSpec.scala
- test/unit/views/shutmucr/ShutMucrSummaryViewSpec.scala
This component is a non-ajax implementation and is the recommended
approach by the HMRC Play UI team, since the previous "GetHelpLink" was
not accessible.
This component does not work locally and it should simply open a new
page. We have been told that this will work in all the other
environments.
> CEDS-2667 Add HMRCReportTechnicalssue component

- app/config/AppConfig.scala
- app/views/components/gds/phaseBanner.scala.html
- conf/application.conf
- run-contact-frontend-sm_local.sh
- test/unit/config/AppConfigSpec.scala
- test/unit/views/PhaseBannerSpec.scala
- test/unit/views/associateucr/MucrOptionsViewSpec.scala
There are 2 issues that are fixed in this PR:
1. `backURL` should have capitalized 'URL'
2. In other environments, the link to contact-frontend was incorrect.
It should be using url, similarly to how we link to Movements in
Declarations service.
> CEDS-2745 Fix contact-frontend url

- app/views/components/gds/gds_main_template.scala.html
On our GDS Design System main template, we manually
add all the footer items which are now out of date.
Changing to use the HMRC frontend lib to add them
dynamically.
> [CEDS-2941] Dynamically load the Footer Links

- app/controllers/consolidations/MucrOptionsController.scala
- app/forms/AssociateUcr.scala
- app/forms/DucrPartDetails.scala
- app/forms/MucrOptions.scala
- app/forms/UcrType.scala
- app/views/components/gds/exportsInputText.scala.html
- conf/messages
- test/it/AssociateUcrSpec.scala
- test/it/AssociateUcrSpecWithIleQueryDisable.scala
- test/unit/controllers/consolidations/AssociateUcrControllerSpec.scala
- test/unit/controllers/consolidations/AssociateUcrSummaryControllerSpec.scala
- test/unit/controllers/consolidations/MucrOptionsControllerSpec.scala
- test/unit/forms/AssociateUcrSpec.scala
- test/unit/forms/DucrPartDetailsSpec.scala
- test/unit/forms/MucrOptionsSpec.scala
- test/unit/services/SubmissionServiceSpec.scala
- test/unit/views/DucrPartDetailsViewSpec.scala
- test/unit/views/associateucr/AssociateUcrViewSpec.scala
- test/unit/views/associateucr/MucrOptionsViewSpec.scala
Update text and remove full stops from end of validation error
messages.
Add separate error messages for empty vs invalid values.
Refactoring of the MucrOptions model class.
> [CEDS-2947] Updating Validation Error Messages Additional work

- app/assets/javascripts/timeoutDialog.js
This file is not needed for timeout to work correctly.
> BAU Remove timeoutDialog.js file

- conf/application.conf
To meet splunk storage requirements.
> CEDS-3650 Add config to stop auditing asset requests

- app/config/AppConfig.scala
- app/controllers/actions/AuthAction.scala
- app/models/AuthKey.scala
- app/utils/HashingUtils.scala
- app/views/unauthorisedEoriInTdr.scala.html
- build.sbt
- conf/application.conf
- conf/messages
- project/AppDependencies.scala
- test/unit/base/MockAuthConnector.scala
- test/unit/config/AppConfigSpec.scala
- test/unit/controllers/ControllerLayerSpec.scala
- test/unit/controllers/actions/AuthActionSpec.scala
- test/unit/controllers/actions/EoriAllowListSpec.scala
- test/unit/handlers/ErrorHandlerSpec.scala
- test/unit/testdata/CommonTestData.scala
- test/unit/testdata/MovementsTestData.scala
- test/unit/views/UnauthorisedEoriInTdrViewSpec.scala
- test/util/connectors/AuthWiremockTestServer.scala
Adding new 'secret.tdrHashSalt' config value that will only be set in the TDR environment.
Adding additional authentication check that if the 'tdrHashSalt' value is present in config, then the user must specify an additional HMRC-CUS-ORG enrolment value of 'TDRSecret' who's value must be a valid hash of the supplied 'EORINumber' value.
> CEDS-4813 Secure Movements FE login on TDR with additional secret value.

- conf/application.conf
- project/plugins.sbt
Adding in settings for GA4 plus general review to comply with standards: https://confluence.tools.tax.service.gov.uk/display/SEC/Content+Security+Policy+Guidance
> CEDS-5089 GA4 Update the Content Security Policy

- app/views/components/gds/exportsInputText.scala.html
- app/views/components/gds/gds_main_template.scala.html
- app/views/location.scala.html
Removing @hmrcTrackingConsentSnippet() as it seems to be pulled in by the template - causing a duplicate consent script to be called on pages. After removal this is still present on the page as expected:
<script
nonce="TtQbtiTBUtVhSJ8p1Upm1Q==" 
src="[http://localhost:12345/tracking-consent/tracking.js](view-source:http://localhost:12345/tracking-consent/tracking.js)"
id="tracking-consent-script-tag"
data-gtm-container="a"
data-language="en"
></script>
> CEDS-5250 - Fixing VNU issues
